---
- name: Nginx web server Installation
  hosts: all

  become: true

  tasks:
  - shell: apt-get upgrade -y; apt-get update

  - name: Installation
    apt:
      name: nginx
      state: latest

  - name: Starting  Nginx
    service:
      name: nginx
      state: started
